---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscache
  labels:
    app: rediscache
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: rediscache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rediscache
    spec:
      containers:
      - name: rediscache
        image: docker.io/library/redis:7.4
        imagePullPolicy: Always
        ports:
        - name: tcp
          containerPort: 6379
        envFrom:
        - configMapRef:
            name: rediscache-env
      terminationGracePeriodSeconds: 180