---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:17.2
        imagePullPolicy: Always
        ports:
        - name: tcp
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-env
      terminationGracePeriodSeconds: 180