name: Generate Aspire Manifest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' # Aspire requires .NET 8 or later

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ vars.GKE_CLUSTER }}
        location: ${{ vars.GKE_ZONE }}
        project_id: ${{ vars.GCP_PROJECT }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Install aspire8
      run: dotnet tool install -g aspirate

    - name: Init aspirate 
      run: /github/home/.dotnet/tools/aspirate init --non-interactive --container-registry "docker.io" --container-repository-prefix "gabrielemessina"
      working-directory: GabrieleMessina.AppHost

    - name: Aspirate generate files
      run: /github/home/.dotnet/tools/aspirate generate --non-interactive --include-dashboard --image-pull-policy "Always" --secret-password ${{ secrets.ASPIRATE_KEY }} --container-registry "docker.io" --container-repository-prefix "gabrielemessina"
      working-directory: GabrieleMessina.AppHost

    # - name: Apply k8s configurations 
      # run: aspirate apply --non-interactive --secret-password ${{ secrets.ASPIRATE_KEY }} && aspirate destroy --non-interactive
      # working-directory: GabrieleMessina.AppHost

    - name: Upload manifest artifact
      uses: actions/upload-artifact@v4
      with:
        name: aspire-manifest
        path: ./aspire-manifest
